spring:
  application:
    name: habit-tracker

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true # Позволит зайти на http://localhost:8080/h2-console и увидеть таблицы

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # create-drop
    show-sql: true

server:
  port: 8080

jwt:
  key: ${JWT_KEY}
  access-token-expiration: 43200000